// Generated by gencpp from file dashan_msg/wheelSpeed.msg
// DO NOT EDIT!


#ifndef DASHAN_MSG_MESSAGE_WHEELSPEED_H
#define DASHAN_MSG_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dashan_msg
{
template <class ContainerAllocator>
struct wheelSpeed_
{
  typedef wheelSpeed_<ContainerAllocator> Type;

  wheelSpeed_()
    : header()
    , leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
    }
  wheelSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _leftwheel_speed_type;
  _leftwheel_speed_type leftwheel_speed;

   typedef float _rightwheel_speed_type;
  _rightwheel_speed_type rightwheel_speed;





  typedef boost::shared_ptr< ::dashan_msg::wheelSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dashan_msg::wheelSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelSpeed_

typedef ::dashan_msg::wheelSpeed_<std::allocator<void> > wheelSpeed;

typedef boost::shared_ptr< ::dashan_msg::wheelSpeed > wheelSpeedPtr;
typedef boost::shared_ptr< ::dashan_msg::wheelSpeed const> wheelSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dashan_msg::wheelSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dashan_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dashan_msg': ['/home/mini/code/outdoor_robot/src/package/dashan_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9f5bb93b9ab85fa68f61bf838b71299";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9f5bb93b9ab85faULL;
  static const uint64_t static_value2 = 0x68f61bf838b71299ULL;
};

template<class ContainerAllocator>
struct DataType< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dashan_msg/wheelSpeed";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
Header header \n\
float32 leftwheel_speed\n\
float32 rightwheel_speed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.leftwheel_speed);
      stream.next(m.rightwheel_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dashan_msg::wheelSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.leftwheel_speed);
    s << indent << "rightwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rightwheel_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DASHAN_MSG_MESSAGE_WHEELSPEED_H
