# 地图参数
map:
  # 路径
  map_img_dir: /home/mini/code/localization_ws/src/indoor_localization/map/map.png
  sizeWidth: 1000
  sizeHeight: 1000
  initx: 386
  inity: 386
  cell_size: 0.05
  frame_id: odom

sensor_model:
  P_occ: 0.6
  P_free: 0.4
  P_prior: 0.5

robot:
  kl: 0.145 # 左轮半径
  kr: 0.145 # 右轮半径
  b: 0.415 # 车半径

# 激光到里程计的外参
robot_laser:
  x: 0.26
  y: 0.0
  theta: 0.0

motion_model:
  alpha1: 0.15
  alpha2: 0.15
  alpha3: 0.15
  alpha4: 0.15

measurement_model:
  sigma: 0.05
  rand_weight: 0.1 # 随机测量的权重
  gaussion_weight: 0.9 # 高斯测量的权重
  scale: 1

particle_filter:
  n_particles: 1000
